#github-actions-yaml

name: CI/CD Pipeline

# Trigger this workflow on push to the main branch

on:
  push:
    branches:
      - master


jobs:
  build_and_deploy:
    runs_on: ubuntu-latest #GitHub will create a temporary VM to run your workflow

    steps:
      - name: checkout_code
        uses: actions/checkout@v3

      - name: setup_docker_buildx
        uses: docker/setup-buildx-action@v3
        
      - name: login_to_dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build_and_push_docker_image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: aisha10/nodejs-demo-app:latest

      - name: logout from dockerhub
        run: docker logout

